### ISSUE TITLE
P4-Ovs installation

### ISSUE THREAD

**Issue by Dscano** [ipdk-io/ovs#45]
Hi,

I follow the guide for installing P4-OVS https://github.com/ipdk-io/ovs/blob/ovs-with-p4/Documentation/intro/install/ovs-with-p4-general.rst. Before to install P4-OVS I installed  `p4-dpdk-target `and I tested it with https://github.com/p4lang/p4-dpdk-target/tree/3344147d9d5dd9e064ac2d98b5088426cc32e191/examples/psa/simple_l2l3_lpm.

Everything was installed without errors, but when i run `./run_ovs.sh ` I get this error.
![Screenshot from 2022-08-09 17-43-32](https://user-images.githubusercontent.com/25779169/183697811-81e2b132-a912-4d01-bfdd-fb531beef4bd.png)

Do you have any clue to solve this issue?

**Comment by stadju** [comment]
Hi, please do the following before ./run_ovs.sh:

source p4ovs_env_setup.sh $SDE_INSTALL

**Comment by Dscano** [comment]
Hi,

I did it and i get the same error
![Screenshot from 2022-08-10 10-12-17](https://user-images.githubusercontent.com/25779169/183851186-d0422ea7-e3b2-4cc2-b8fd-06a0abdcc1e8.png)
.
I looked for the file  `libtdi_pna.so` and i get:
![Screenshot from 2022-08-10 10-15-14](https://user-images.githubusercontent.com/25779169/183851428-d6435b98-60f0-4abf-b291-557167332ddc.png)
![Screenshot from 2022-08-10 10-15-35](https://user-images.githubusercontent.com/25779169/183851439-27f710dd-04fa-4db5-8f05-e94c766ce5d0.png)

So seems that everything is installed. More in detail, my goal is install p4-ovs and use the psa architecture on a Ubuntu 20.4 workstation with i7 CPU. Do you have any clue to solve my issue? should i have to reinstall everything ( p4-dpdk+p4-ovs)?

**Comment by stadju** [comment]
Can you echo $LD_LIBRARY_PATH?

Below are my installation steps on Ubuntu 20.04 for your reference:

//////install p4-dpdk-target
mkdir p4sde
cd p4sde
mkdir install
export SDE=$PWD
export SDE_INSTALL=$SDE/install

git clone https://github.com/p4lang/p4-dpdk-target.git --recursive p4-dpdk-target
cd p4-dpdk-target/
git checkout f0efcc2d904212598f5629181d0481038df20131
./autogen.sh
./configure --prefix=$SDE_INSTALL --with-generic-flags=yes
make -j64
make install

/////install P4OVS
git clone https://github.com/ipdk-io/ovs.git p4ovs
cd p4ovs
git submodule update --init --recursive
./install_dep_packages.sh $PWD
./build-p4ovs.sh $SDE_INTSALL
source p4ovs_env_setup.sh $SDE_INSTALL
./run_ovs.sh

**Comment by Dscano** [comment]
Hi,
I get when i run `echo $LD_LIBRARY_PATH?`
![Screenshot from 2022-08-11 20-54-29](https://user-images.githubusercontent.com/25779169/184217596-a271665e-bdc4-4a93-aa4e-4476a2a9ed25.png)
Is it correct?
I installed p4-dpdk latest "version", I didn't install this "version" `0efcc2d904212598f5629181d0481038df20131`. I'll try to reinstall everything.

**Comment by stadju** [comment]
Your LD_LIBRARY_PATH looks correct.  Not sure if it matters but please make sure PYTHONPATH and PYTHONHOME are unset during installation.  They're only needed to be set to run bf_switchd.
If you specify a directory for install_dep_packages.sh [ovs_dep_install], you need to specify: run_ovs.sh [ovs_dep_install]

**Comment by Dscano** [comment]
I follow your guide https://github.com/ipdk-io/ovs/issues/45#issuecomment-1211518910 and I have checked that PYTHONPATH and PYTHONHOME are unset during installation.
But I get the same error `ovs-vswitchd: error while loading shared libraries: libtdi_pna.so: cannot open shared object file: No such file or directory`. I did the installation workflow 3 times but I get the same result.
![Screenshot from 2022-08-12 14-41-58](https://user-images.githubusercontent.com/25779169/184356146-14a0463e-8f01-44e8-8b7c-4eb1233e6d3c.png)
![Screenshot from 2022-08-12 14-42-31](https://user-images.githubusercontent.com/25779169/184356163-98fd52f2-7e6d-4bef-80f8-d9837aea81f9.png)

**Comment by stadju** [comment]
If you can share your command history for installation, I can try to reproduce it.  Or you can debug/print the path variables in run_ovs.sh.  Btw., I did the installation as root so you might want to try that.

**Comment by Dscano** [comment]
Hi,

I reinstalled everything as root and it woks:
![Screenshot from 2022-08-16 13-58-35](https://user-images.githubusercontent.com/25779169/184874483-c5788e48-358f-4049-821a-e4aef11766dc.png)
![Screenshot from 2022-08-16 13-58-39](https://user-images.githubusercontent.com/25779169/184874495-b29f7346-c9a4-4bef-ab6a-cf6bda92d6b2.png)

But now I have this issue even if I have installed `./install_dep_packages.sh` so in theory I should have everything installed. More in details in my machine I have Ubuntu 20.4 with python 3.8 and via `update-alternatives` when I run python I call python3.8.
![Screenshot from 2022-08-16 15-57-38](https://user-images.githubusercontent.com/25779169/184899036-37b179ce-6a72-4f71-acde-7599baae13da.png)

**Comment by Dscano** [comment]
I have solved my issues:

1.  I have solved the `google.rpc` problem via`pip 3install --upgrade --force-reinstall -r requirements.txt`, `requirements.txt ` is here https://github.com/ipdk-io/ovs/tree/ovs-with-p4/Documentation
2.  I have also installed `pip3 install p4runtime`

After that `ovs-p4ctl `works
