### ISSUE TITLE
grpc server ip address needs to be configurable

### ISSUE THREAD

**Issue by nupurjai** [ipdk-io/ovs#46]
grpc server and port configurations should be configurable in stratum through a config file. Applies to grpc and gnmi servers.

**Comment by ffoulkes** [comment]
My apologies, I didn't realize there were issues against the ovs repository.

Stratum (the gRPC server for gNMI and p4rt) is not part of OVS in the split architecture (now called P4 Control Plane). If this is still an issue, please refile it against ipdk-io/stratum-dev.
